version: "3.5"

services:
  chrome:
    image: selenium/node-chrome
    container_name: chrome
    shm_size: 3gb
    depends_on:
      - selenium-hub
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=12
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD= true

    logging:
      driver: local

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

    logging:
      driver: local


  olx:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/code
    network_mode: host
